export const LOGIN_FINISHED = 'LOGIN_FINISHED';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const ERROR_FETCHING = 'ERROR_FETCHING';
export const ERROR_RESET = 'ERROR_RESET';
export const USER_CREATED = 'USER_CREATED';
export const USER_LOGOUT = 'USER_LOGOUT';
